/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as OnlineBookingRouteImport } from './routes/online-booking'
import { Route as TariffRouteImport } from './routes/tariff'
import { Route as TourPackagesRouteImport } from './routes/tour-packages'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const OnlineBookingRoute = OnlineBookingRouteImport.update({
  id: '/online-booking',
  path: '/online-booking',
  getParentRoute: () => rootRouteImport,
} as any)
const TariffRoute = TariffRouteImport.update({
  id: '/tariff',
  path: '/tariff',
  getParentRoute: () => rootRouteImport,
} as any)
const TourPackagesRoute = TourPackagesRouteImport.update({
  id: '/tour-packages',
  path: '/tour-packages',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/online-booking': typeof OnlineBookingRoute
  '/tariff': typeof TariffRoute
  '/tour-packages': typeof TourPackagesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/online-booking': typeof OnlineBookingRoute
  '/tariff': typeof TariffRoute
  '/tour-packages': typeof TourPackagesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/online-booking': typeof OnlineBookingRoute
  '/tariff': typeof TariffRoute
  '/tour-packages': typeof TourPackagesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/online-booking'
    | '/tariff'
    | '/tour-packages'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/online-booking'
    | '/tariff'
    | '/tour-packages'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/online-booking'
    | '/tariff'
    | '/tour-packages'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  OnlineBookingRoute: typeof OnlineBookingRoute
  TariffRoute: typeof TariffRoute
  TourPackagesRoute: typeof TourPackagesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/online-booking': {
      id: '/online-booking'
      path: '/online-booking'
      fullPath: '/online-booking'
      preLoaderRoute: typeof OnlineBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tariff': {
      id: '/tariff'
      path: '/tariff'
      fullPath: '/tariff'
      preLoaderRoute: typeof TariffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tour-packages': {
      id: '/tour-packages'
      path: '/tour-packages'
      fullPath: '/tour-packages'
      preLoaderRoute: typeof TourPackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  OnlineBookingRoute: OnlineBookingRoute,
  TariffRoute: TariffRoute,
  TourPackagesRoute: TourPackagesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
